# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1304feac13bbaf10c62db9f498cad73711029524e8d6bb9493481c189b3defc31da6e51b6ee3f046405ed073d3879ffd4d259de9dfe34903f738be16b767157

test:
  secret_key_base: 2ca56b117d926d7adf64abdb0f7d750ed66124ba1e64f164ebc17dfe0d7056caeb540b8ff50ca1d17f39a0e4b595b4ee3ef8c56989b2d1f04b41d94a3fd51ad4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
